/* Server version: WI-V6.3.7.18553 Firebird 2.1 
   SQLDialect: 3. ODS: 11.1. Forced writes: On. Sweep interval: 20000.
   Page size: 16384. Cache pages: 2048 (32768 Kb). Read-only: False. */
SET CLIENTLIB 'C:\Windows\System32\gds32.dll';
SET NAMES WIN1251;

SET SQL DIALECT 3;

CONNECT 'D:\WORK\KOMUN\dolg\DOLG.GDB' USER 'sysdba' PASSWORD 'masterkey';

SET AUTODDL ON;

RECONNECT;

ALTER TABLE PERIOD DROP CONSTRAINT PK_PERIOD;

RECONNECT;

ALTER TABLE ORGAN DROP CONSTRAINT INTEG_75;

RECONNECT;

ALTER TABLE OPL DROP CONSTRAINT INTEG_46;

RECONNECT;

ALTER TABLE OBOR DROP CONSTRAINT INTEG_73;

RECONNECT;

ALTER TABLE KART DROP CONSTRAINT INTEG_72;

/* Dropping trigger... */
DROP TRIGGER KART_BI;

DROP TRIGGER OBOR_BI;

DROP TRIGGER OPL_BI;

DROP TRIGGER ORGAN_BI;

DROP TRIGGER PERIOD_BI;


/* Drop View... */
DROP VIEW VW_OBOR;


RECONNECT;

/* Drop tables... */
DROP TABLE KART;

DROP TABLE OBOR;

DROP TABLE OPL;

DROP TABLE ORGAN;

DROP TABLE UL;

DROP TABLE WID;


/* Dropping generators... */
DROP GENERATOR GEN_KART_ID;

DROP GENERATOR GEN_NOTE_ID;

DROP GENERATOR GEN_OBOR_ID;

DROP GENERATOR GEN_OPL_ID;

DROP GENERATOR GEN_ORGAN_ID;


/* DROP: -- GRANT ALL ON VW_OBOR TO SYSDBA WITH GRANT OPTION */
REVOKE ALL ON VW_OBOR FROM SYSDBA;

