/******************************************************************************/
/***          Generated by IBExpert 2015.7.26.1 01.10.2020 8:17:27          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

CREATE DATABASE 'D:\WORK\KOMUN\dolg\DOLG\DOLG.GDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET NONE;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE LG_COD (
    ID   INTEGER NOT NULL,
    WID  VARCHAR(2),
    COD  INTEGER
);



/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE LG_COD ADD CONSTRAINT PK_LG_COD PRIMARY KEY (ID);
